// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgutieyztvfpggaxewjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndndXRpZXl6dHZmcGdnYXhld2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDc3NDMsImV4cCI6MjA3NDcyMzc0M30.tdN6-XCy8NltpZ6KfhWENHLIE_X4n4SqoXI-nFZZXsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});